# Site settings
title: The Patrick.Drives Blog
email: patrickabalex@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Car Nerd Blog – Performance Driving, Vehicle Engineering, and Automotive Photography
baseurl:  # the subpath of your site, e.g. /blog/
url:  patrickdrives.github.io  # the base hostname & protocol for your site
github_username:  patrickdrives

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  driving:
    output: true
    permalink: /driving/:path/


